# Generated by Django 3.0.7 on 2022-01-31 00:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
